check each script is called from the main install script

diff --git a/modules/default/desktop b/modules/default/desktop
--- a/modules/default/desktop
+++ b/modules/default/desktop
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 # OPTIMALLY THIS SCRIPT SHOULD BE RUN BEFORE WALLPAPERS, BEAR IN MIND ALPHABETICALLY
 
 # tell xfconf to arrange the titlebar buttons in the right order
diff --git a/modules/default/icons b/modules/default/icons
--- a/modules/default/icons
+++ b/modules/default/icons
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 KORA_INSTALL_PATH="/usr/share/icons/kora"
 
 # Remote leftover directory if exists
diff --git a/modules/default/keybindings b/modules/default/keybindings
--- a/modules/default/keybindings
+++ b/modules/default/keybindings
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 # allow multiple shortcuts to use super key
 sudo dnf -y install git gcc make libX11-devel libXtst-devel pkgconfig
 gclonecd https://github.com/hanschen/ksuperkey.git
diff --git a/modules/default/login b/modules/default/login
--- a/modules/default/login
+++ b/modules/default/login
@@ -1,3 +1,8 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 cp $SKYOS_REPO_PATH/res/login/face.png $HOME/.face
diff --git a/modules/default/shell b/modules/default/shell
--- a/modules/default/shell
+++ b/modules/default/shell
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 # Install and switch to zsh
 sudo dnf install -y zsh
 chsh -s $(which zsh)
diff --git a/modules/default/taskbar b/modules/default/taskbar
--- a/modules/default/taskbar
+++ b/modules/default/taskbar
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 sudo dnf install -y xfce4-docklike-plugin xfce4-panel-profiles
 
 TBAR=skyos-taskbar
diff --git a/modules/default/terminal b/modules/default/terminal
--- a/modules/default/terminal
+++ b/modules/default/terminal
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 #terminalrc location as a variable to eliminate repetition
 XFTERM_RC="$HOME/.config/xfce4/terminal/terminalrc"
 
diff --git a/modules/default/theme b/modules/default/theme
--- a/modules/default/theme
+++ b/modules/default/theme
@@ -1,4 +1,10 @@
 #!/bin/bash
+
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 cd $SKYOS_BUILD_PATH
 
 sudo dnf -y install sassc
diff --git a/modules/default/wallpapers b/modules/default/wallpapers
--- a/modules/default/wallpapers
+++ b/modules/default/wallpapers
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 # install wallpapers to global directory
 BG_PATH=/usr/share/backgrounds/SkyOS
 sudo mkdir -p $BG_PATH
diff --git a/modules/optional/minecraft b/modules/optional/minecraft
--- a/modules/optional/minecraft
+++ b/modules/optional/minecraft
@@ -1,3 +1,8 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 flatpak install -y --noninteractive flathub com.mojang.Minecraft
diff --git a/modules/optional/rpmfusion b/modules/optional/rpmfusion
--- a/modules/optional/rpmfusion
+++ b/modules/optional/rpmfusion
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 # install RPM Fusion free repo
 sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
 # install RPM Fusion nonfree repo
diff --git a/modules/optional/steam b/modules/optional/steam
--- a/modules/optional/steam
+++ b/modules/optional/steam
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! [[ $SHLVL -gt 2 ]]; then
+  echo "This script is not designed to be ran individually. Failing"
+  exit 1
+fi
+
 # ensure rpm fusion nonfree is enabled
 SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
 $SCRIPT_DIR/rpmfusion
